# Generated by Django 3.0.4 on 2021-02-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.FileField(upload_to='testimonials/'),
        ),
    ]
